config/routes.rb
Rails.application.routes.draw do

  resources :likes, only:[:create]
  resources :sessions, only:[:new, :create, :destroy]
  resources :cities, only:[:show]
  resources :users, only:[:show, :new, :create]
  resources :gossips

  get '/team', to: 'page#team'
  get '/welcome/:input', to: 'page#welcome' 

  root 'page#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag_joins
  has_many :tags, through: :gossip_tag_joins
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/models/gossip_tag_join.rb
class GossipTagJoin < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :private_message_recipient_joins
  has_many :recipients, through: :private_message_recipient_joins
end

app/models/private_message_recipient_join.rb
class PrivateMessageRecipientJoin < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tag_joins
  has_many :gossips, through: :gossip_tag_joins
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  belongs_to :city

  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :private_message_recipient_joins
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "private_message_recipient_join"
  has_many :likes
  
  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:new]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
     @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)
    if @gossip.save 
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid gossip parameters !'
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    @gossip.update(post_params)
    redirect_to root_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    Like.create(user: User.find_by(id: params[:user_id]), likeable: Gossip.find_by(id: params[:gossip_id]))
    redirect_to gossip_path(id: params[:gossip_id])
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  def index
    @gossips = Gossip.all
  end

  def team

  end


  def contact

  end

  def welcome
    puts "$" * 60
    puts params[:input]
    puts "$" * 60
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      log_in(user)
      remember(user)
      redirect_to root_path
    else
      flash.now[:danger] = '@mail/password invalide !'
      render 'new'
    end
  end

  def destroy
    log_out(current_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    city = City.find_by(name: 'Web')
    @user = User.new(name: params[:name], description: params[:description], city: city, email: params[:email], password: params[:password])
    if @user.save
      log_in(@user) 
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'Invalid user parameters !'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64  
    user.remember(remember_token)

    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    user.update(remember_digest: nil)

    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cities/show.html.erb
<div class="city">
  <h3> <%= @city.name %> </h3>
  <p>Pas grand chose à dire sur cette ville pour l'instant, mais essayez de revenir plus tard :-)</p>
</div>

<section>  <%= link_to "ReToUr aUx PoTiNs", root_path, class:"btn btn-outline-dark" %> </section>

app/views/gossips/edit.html.erb
<%= form_for @gossip do |f| %>

  <div class='form-group text-center mb-5'>
    <label>Nouveau titre</label>
    <%= f.text_field :title, class: 'form-control text-center' %>
  </div>

  <div class='form-group text-center mb-5'>
    <label>Nouveau contenu</label>
    <%= f.text_field :content, class: 'form-control text-center' %>
  </div>

  <div class='form-group text-center'>
    <button type='submit' class="btn-info">Appliquer les modifications</button>
  </div>

<% end %>

app/views/gossips/new.html.erb
<div class="list-group-item text-center w-75 mx-auto mt-5">
  <h2 class="mb-5">CRéaTiOn d'uN PoTiN</h2>
  <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="gossip-creation__title"> 
      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @gossip.title %>
    </div>
    <div class="gossip-creation__content"> 
      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'content', @gossip.content %>
    </div>
    <div class="gossip-creation__submit-button">
      <%= submit_tag "CRéeR le PoTiN" %>
    </div>
  <% end %>
</div>

app/views/gossips/show.html.erb
<div class="list-group w-75 mx-auto mt-5">
<small><%= @gossip.user.name + ' | ' + @gossip.user.city.name %></small>
  <div class="list-group-item mt-2">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-4"><%= @gossip.title %></h5>
    </div>
    <small class="text-muted"><%= @gossip.content %></small>
    <p class="mt-2 text-end text-success">Likes : <%= @gossip.likes.length %></p>
    <div class="gossip__actions">
      <%= link_to "Voir le profil de " + @gossip.user.name, user_path(@gossip.user.id), class: "btn btn-outline-primary p-2 my-2" %>
      <% if current_user == @gossip.user %>
        <%= link_to "Liker le PoTiN", likes_path(user_id: current_user, gossip_id: @gossip.id), method: :post, class: "btn btn-outline-success p-2 my-2" %>
        <%= link_to "Editer", edit_gossip_path(@gossip.id), class: "btn btn-outline-secondary p-2 my-2" %>
        <%= link_to "Supprimer", gossip_path(@gossip.id), method: :delete, class: "btn btn-outline-danger p-2 my-2" %>
      <%end%>
    </div>
  </div>
</div>

<div class="comments list-group w-75 text-center mx-auto m-5">
  <h2> Commentaires </h2>
  <% @gossip.comments.each do|c| %>
  <div class="list-group-item">
    <p> <%= c.user.name + " | " + c.content %> </p>
    <p class="text-success"> Likes : <%= c.likes.length %></p>
    </div>
  <%end%>
</div>

<section>  <%= link_to "ReToUr aUx PoTiNs", root_path, class:"btn btn-outline-dark" %> </section>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/users/create.html.erb
<h2>Bienvenue <%= @user.name %> !</h2>

app/views/users/new.html.erb
<% flash.each do |key, value| %>
  <div class="flash <%= key %>"><%= value %></div>
<% end %>

<%= form_tag url_for(action: 'create'), method: "post" do %>

  <%= label_tag 'Pseudo' %>
  <%= text_field_tag 'name', @name %>

  <%= label_tag 'Description' %>
  <%= text_field_tag 'description', @description %>

  <%= label_tag 'eMail' %>
  <%= text_field_tag 'email', @email %>
  
  <%= label_tag 'Mot de passe' %>
  <%= password_field_tag 'password', @password %>

  <%= submit_tag "Créer le compte" %>

<% end %>

app/views/users/show.html.erb
<div class="profile">
  <h2><%= @user.name %> </h2>
  <h4>Ville: <%= @user.city.name %> </h4> <br/>
  <p> <%= @user.description %> </p>
  <div class="profile__actions">
    <%= link_to "Voir la ville de " + @user.name, city_path(@user.city.id), class: "btn btn-outline-light p-2 mt-5" %>
  </div>
</div>


<section>  <%= link_to "ReToUr aUx PoTiNs", root_path, class:"btn btn-outline-dark" %> </section>