config/routes.rb
Rails.application.routes.draw do

  resources :likes, only:[:create]
  resources :sessions, only:[:new, :create, :destroy]
  resources :cities, only:[:show]
  resources :users, only:[:show, :new, :create]
  resources :gossips

  get '/team', to: 'page#team'
  get '/welcome/:input', to: 'page#welcome' 

  root 'page#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tag_joins
  has_many :tags, through: :gossip_tag_joins
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
end

app/models/gossip_tag_join.rb
class GossipTagJoin < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :private_message_recipient_joins
  has_many :recipients, through: :private_message_recipient_joins
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tag_joins
  has_many :gossips, through: :gossip_tag_joins
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  belongs_to :city

  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :private_message_recipient_joins
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "private_message_recipient_join"
  has_many :likes
  
  def remember(remember_token)
    remember_digest = BCrypt::Password.create(remember_token)
    self.update(remember_digest: remember_digest)
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:new]

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
     @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)
    if @gossip.save 
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid gossip parameters !'
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    post_params = params.require(:gossip).permit(:title, :content)
    @gossip.update(post_params)
    redirect_to root_path
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    Like.create(user: User.find_by(id: params[:user_id]), likeable: Gossip.find_by(id: params[:gossip_id]))
    redirect_to gossip_path(id: params[:gossip_id])
  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController
  
  def index
    @gossips = Gossip.all
  end

  def team

  end


  def contact

  end

  def welcome
    puts "$" * 60
    puts params[:input]
    puts "$" * 60
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    city = City.find_by(name: 'Web')
    @user = User.new(name: params[:name], description: params[:description], city: city, email: params[:email], password: params[:password])
    if @user.save
      log_in(@user) 
      redirect_to user_path(@user.id)
    else
      flash.now[:danger] = 'Invalid user parameters !'
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    if session[:user_id]
      User.find_by(id: session[:user_id])
    elsif cookies[:user_id]
      user = User.find_by(id: cookies[:user_id])
      if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
        log_in user
        current_user = user
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    remember_token = SecureRandom.urlsafe_base64  
    user.remember(remember_token)

    cookies.permanent[:user_id] = user.id
    cookies.permanent[:remember_token] = remember_token
  end

  def forget(user)
    user.update(remember_digest: nil)

    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out(user)
    session.delete(:user_id)
    forget(user)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Le SiTe dU pOtiN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-dark bg-dark p-4">
        <h2> <%= link_to "LE siTe du PoTiN", root_path, class:"text-light mx-4" %> </h2>
        <form class="form-inline">
          <%= link_to "Infos & Contact", team_path, class: "text-muted mx-3 mx-lg-4" %>
          <% if current_user %>
            <%= link_to "RéDigEr Un PoTiN", new_gossip_path, class: "text-light mx-3" %>
            <%= link_to "MoN ProFiL", root_path, :class => "text-light btn btn-outline-primary mx-3" %>
            <%= link_to "Déconnexion", session_path(session.id), method: :delete, :class => "btn btn-outline-warning mx-3" %>
          <% else %>
            <%= link_to "Connexion | Inscription", new_session_path, :class => "btn btn-outline-warning" %>  
          <% end %>
        </form>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<div class="list-group w-75 mx-auto">
  <% @gossips.reverse_each do |g| %>
    <a href="<%=gossip_path(g.id)%>" class="list-group-item list-group-item-action">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-4"><%= g.title %></h5>
        <small><%= g.user.name + ' | ' + g.user.city.name %></small>
      </div>
      <small class="text-muted"><%= g.content %></small>
    </a>
  <% end %>
</div>

app/views/page/team.html.erb
<section>
  <div class="card" style="width: 22rem;">
    <%= image_tag('tim.png')%>
    <div class="card-body">
      <h5 class="card-title">Timothée GiMBERT</h5>
      <h6 class="card-subtitle mb-2 text-muted">Développeur principal</h6>
      <a href="https://github.com/TimotheeGimbert" target="_blank" class="btn btn-success my-3">Voir le GitHub</a>
    </div>
  </div>
  <div class="card" style="width: 22rem;">
    <%= image_tag('xavier.png')%>
    <div class="card-body">
      <h5 class="card-title">Xavier KiNDERF</h5>
      <h6 class="card-subtitle mb-2 text-muted">Collaborateur</h6>
      <a href="https://github.com/FabCom" target="_blank" class="btn btn-warning my-3">Voir le GitHub</a>
    </div>
  </div>
  <div class="card" style="width: 22rem;">
    <%= image_tag('gautier.png')%>
    <div class="card-body">
      <h5 class="card-title">Gautier BlONDEL</h5>
      <h6 class="card-subtitle mb-2 text-muted">Collaborateur</h6>
      <a href="https://github.com/GautierBlondel" target="_blank" class="btn btn-primary my-3">Voir le GitHub</a>
    </div>
  </div>
  <div class="card" style="width: 22rem;">
    <%= image_tag('luis.png')%>
    <div class="card-body">
      <h5 class="card-title">Luis LoREGERES</h5>
      <h6 class="card-subtitle mb-2 text-muted">Collaborateur</h6>
      <a href="https://github.com/looping124" target="_blank" class="btn btn-danger my-3">Voir le GitHub</a>
    </div>
  </div>
</section>

<section>  <%= link_to "ReToUr aUx PoTiNs", root_path, class:"btn btn-outline-dark" %> </section>

app/views/page/welcome.html.erb
<h1> CUSTOM WELCOME PAGE </h1></br></br>
<p> Pas mal tu as découvert la page secrète, avec ton param <%=params[:input]%> </p>